repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: sort-simple-yaml
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
        args: ['--maxkb=1200']
      - id: check-docstring-first
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: debug-statements
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: "Sort imports"
        args: ["--profile", "black", "--filter-files"]

  - repo: https://github.com/psf/black
    rev: "23.7.0"
    hooks:
      - id: black
        name: "Black"
  - repo: https://github.com/commitizen-tools/commitizen
    rev: 3.6.0
    hooks:
      - id: commitizen
        name: "Check conventional commits"
        stages: [commit-msg]
